{% set version = "0.1.1" %}

package:
  name: jnv
  version: {{ version }}

source:
  url: https://github.com/ynqa/jnv/archive/v{{ version }}.tar.gz
  sha256: 40fdb9de56d7ad55f7f3c52440ba7920f9aaffec07d59881b04e87a6facc5d28

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - autoconf
    - clangdev
    - libtool
    - pkg-config
    - cargo-bundle-licenses

test:
  commands:
    - jnv --help

about:
  home: https://github.com/ynqa/jnv
  license: MIT
  summary: interactive JSON filter using jq
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch