context:
  version: 0.2.21

recipe:
  name: colbert-ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/colbert-ai/colbert_ai-${{ version }}.tar.gz
    sha256: a8d6fdb4e2272f2b08ed37f8e5096072160d8415d1e40585751898b77e625bab

build:
  number: 0

outputs:
  - package:
      name: colbert-ai
      version: ${{ version }}

    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools
      run:
        - python >=3.8
        - bitarray
        - datasets
        - flask
        - gitpython
        - python-dotenv
        - ninja
        - scipy
        - tqdm
        - transformers
        - pytorch
        - ujson

    tests:
      - python:
          imports:
            - colbert
          pip_check: false

about:
  homepage: https://github.com/stanford-futuredata/ColBERT
  summary: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
